{{- if .Values.opaConfig }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "workato_opa.fullname" . }}-config
data:
{{- range $path, $config := .Values.opaConfig }}
  {{ $path }}: |
{{ tpl $config $ | indent 4 -}}
{{- end -}}
{{- end -}}
